import os

os.system(r'python C:/xyzy/1lhjr/1scrb/zhishuzhangfu0.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/zhishuzhangfu5.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/zhishuzhangfu10.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/zhishuzhangfu20.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/zhishuzhangfu60.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/zhishuzhangfu120.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/zhishuzhangfu250.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/zhishuzhangfuhebing.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/zhishuzijin0.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/zhishuzijin1.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/zhishuzijin2.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/zhishuzijin2topng.py')

os.system(r'python C:/xyzy/1lhjr/1scrb/fenggezhangfu0.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/fenggezhangfu5.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/fenggezhangfu10.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/fenggezhangfu20.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/fenggezhangfu60.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/fenggezhangfu120.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/fenggezhangfu250.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/fenggezhangfuhebing.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/fenggezijin0.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/fenggezijin1.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/fenggezijin2.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/fenggezijin2topng.py')

os.system(r'python C:/xyzy/1lhjr/1scrb/hangyezhangfu0.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/hangyezhangfu5.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/hangyezhangfu10.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/hangyezhangfu20.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/hangyezhangfu60.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/hangyezhangfu120.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/hangyezhangfu250.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/hangyezijin0.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/hangyezijin1.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/hangyezijin2.py')
os.system(r'python C:/xyzy/1lhjr/1scrb/hangyezijin2topng.py')

os.system(r'python C:/xyzy/1lhjr/1scrb/zztopdf.py')