    df=c.csd(code,"CLOSE",days,""+date+"",f"period={period},adjustflag=3,curtype=1,order=1,market=CNSESH,RowCODES=none,Ispandas=1")
    df.CODES = df.CODES.str.replace('399373.SZ','大盘价值')
    df.CODES = df.CODES.str.replace('399377.SZ','小盘价值')
    df.CODES = df.CODES.str.replace('399372.SZ','大盘成长')
    df.CODES = df.CODES.str.replace('399376.SZ','小盘成长')
    df.CODES = df.CODES.str.replace('CI005917.CI','金融')
    df.CODES = df.CODES.str.replace('CI005918.CI','周期')
    df.CODES = df.CODES.str.replace('CI005919.CI','消费')
    df.CODES = df.CODES.str.replace('CI005920.CI','成长')
    df.CODES = df.CODES.str.replace('CI005921.CI','稳定')
    fig = px.line(df,x='DATES', y='CLOSE',color=df.CODES)
